# Required metadata
sonar.projectKey=aceest-fitness-api
sonar.projectName=ACEest Fitness App
sonar.projectVersion=1.0

# Path to source directories (current directory)
sonar.sources=.

# Exclude test folders and environment folders from the main code analysis
sonar.exclusions=tests/**, venv/**, **/*.html, **/*.css, **/*.db

# Path to test directories
sonar.tests=tests

# Language
sonar.language=py

# Tell SonarQube where to find the coverage report (we will generate this with pytest)
sonar.python.coverage.reportPaths=coverage.xml